### ISSUE TITLE
tidy up code

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WRODataPlatform#20]
CKAN core should be a dependency; we should not fork it or change it (unless we plan to fix a bug, contribute etc.). Therefore the only code in this repo should consist of extensions we develop, as per https://github.com/kartoza/ckanext-dalrrd-emc-dcpr. 

A related comment from Ricardo:

> you may be able to put that custom logic in your plugin rather than in core CKAN - that would be cleaner, if at all possible
for logic/action/create.py you should be able to create a custom action that overrides the default CKAN action. look into the CKAN docs for more on that. We are doing it in the EMC project, you can look there too. Basically you need to make your plugin implement the IActions interface
https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IActions
as for the custom stuff you put in the resource.py module, maybe it is possible to also keep that in the plugin code. Ideally you do not want to be modifying the core CKAN package here, as that may make it harder to upgrade to newer CKAN versions some time down the line

**Comment by Mohab25** [comment]
Adding to this ticket:
all of the bigquery logic should in one place, specially the different views (bq tabular view, map view, mash view ..etc.) by having multiple plugin files in one extension (see https://github.com/ckan/ckan/discussions/6643#discussioncomment-3406036) , make sure all the related css  is contained within the extension. Pull data once at a resource level and distribute the data to the different functions instead of having the each view making a query to speedup and limit queries.

**Comment by Mohab25** [comment]
several changes made to the environment we run CKAN in, we don't have a containerized app at the moment, closing this for irrelevancy.
