### ISSUE TITLE
Weather data import

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WRODataPlatform#28]
from @mikev3003 18 May:
> For our next WRC deliverable (30 June), we need to report on efforts to make weather data available through the platform. For a free option, we are very interested in NASAPower data (https://power.larc.nasa.gov/). Could one of your team please explore the possibility of pulling in all the weather data for South Africa on a monthly basis?

**Comment by mikev3003** [comment]
@vermeulendivan Hi Divan how is it going with the POWER weather data upload?

**Comment by vermeulendivan** [comment]
@mikev3003 Hi Michael! 'climatology' and 'monthly' is done ('monthly' includes 'annual'). The daily is still running, this is taking a long time because its a lot of data. I have four runs going at the same time, but cannot run more than that because the NASA site has a request limit. Most of the data is done from 1981 to the end of 2005, and runs has started for 2006 to 2022.

Those 'temp' tables are only used for appending to tables during downloading/uploading and is automatically deleted once done.
![image](https://user-images.githubusercontent.com/79740955/178689831-3f3691d4-6892-40cf-af20-0943fb2031dc.png)

**Comment by vermeulendivan** [comment]
The code for this is mostly done, except maybe for any unexpected issues which may pop up. How to deploy the code to Google cloud, set up a function, and set the scheduler has been documented. This will/can be deployed to the main wro project on GCP, just need to discuss a few aspects with @mikev3003

**Comment by vermeulendivan** [comment]
This is working as it should. Will therefore close this issue.
![image](https://user-images.githubusercontent.com/79740955/190617865-241f6cb4-785a-4127-ba8c-3e2b626dd3e0.png)

**Comment by mikev3003** [comment]
Impressive work @vermeulendivan - thank you!
